// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApV4UeXYzBNStawLKmSglGCqQk5jYKfOs',
    appId: '1:992176784302:web:cd3fc15a4cfb3422a0fe3f',
    messagingSenderId: '992176784302',
    projectId: 'vocab-coach-17847',
    authDomain: 'vocab-coach-17847.firebaseapp.com',
    storageBucket: 'vocab-coach-17847.appspot.com',
    measurementId: 'G-GY7ELDGL14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgNXI15llltKWv49YWHQM35SoLnA6Jw7g',
    appId: '1:992176784302:android:3b48bdc6ae616945a0fe3f',
    messagingSenderId: '992176784302',
    projectId: 'vocab-coach-17847',
    storageBucket: 'vocab-coach-17847.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdcd2ky5wmmCZa9Z6jgZZSJg4fu7fmFCI',
    appId: '1:992176784302:ios:446029560fe85937a0fe3f',
    messagingSenderId: '992176784302',
    projectId: 'vocab-coach-17847',
    storageBucket: 'vocab-coach-17847.appspot.com',
    iosBundleId: 'com.example.vocabularyCoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdcd2ky5wmmCZa9Z6jgZZSJg4fu7fmFCI',
    appId: '1:992176784302:ios:7e2dec9658b8574fa0fe3f',
    messagingSenderId: '992176784302',
    projectId: 'vocab-coach-17847',
    storageBucket: 'vocab-coach-17847.appspot.com',
    iosBundleId: 'com.example.vocabularyCoach.RunnerTests',
  );
}
